### ISSUE TITLE
loadOrders does not work when there are products with variant options

### ISSUE THREAD

**Issue by bayareacoder** [outgrow/reaction-dummy-data#4]
When you have a catalog in which (some) product variants have options, the `loadOrders` mutation will fail if it randomly selects such a product.
Reason is that the `loadOrders` mutation always just selects the first `variantId` at the "variant" level, while it should select a `variantId` at the option level in that case.

See this code:
```
    const productVariant =
      randomProduct.product.variants && randomProduct.product.variants.length > 0 && randomProduct.product.variants[0];
```

The console will actually log an error since when the order is placed, `placeOrder` will try to look up the (productId, variantId) combination during `buildOrderItem` and will correctly only look for variantIds at the option level, if the product variant has options. Inside `api-plugin-catalogs`, file `findVariantInCatalogProduct.js`:
```
catalogProduct.variants.forEach((variant) => {
    if (variant.options && variant.options.length) {
      variant.options.forEach((option) => {
        if (option.variantId === variantId) {
          // ....
      });
    } else if (variant.variantId === variantId) {
// ...
}
```
So it does not consider a `variantId` at the variant level if the variant has options

The error seen will be this:
`ERROR Reaction: Product with ID SAn4M6BpA9GvDyxXZ has no variant with ID JKSqfxb6f7SpeJ5qD`

SOLUTION:
- replace above code by:
```
    const productVariant =
      randomProduct.product.variants &&
      randomProduct.product.variants.length > 0 &&
      randomProduct.product.variants[0].options && randomProduct.product.variants[0].options.length
        ? randomProduct.product.variants[0].options[0]
        : randomProduct.product.variants[0];
```

**Comment by loan-laux** [comment]
Thanks @bayareacoder, and sorry for the very late reply here. That's an obvious bug which I'm sorry took so long to fix. Version `1.1.2` will now work with options.
